default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:

development:
  <<: *default
  database: skus_dev

test:
  <<: *default
  database: skus_test

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
